-- DROP DATABASE
DROP DATABASE IF EXISTS ecommerce_db;

-- CREATE DATABASE
CREATE DATABASE ecommerce_db;

CREATE TABLE category (
    id INTEGER NOT NULL AUTO_INCREMENT,
    category_name VARCHAR(30) NOT NULL,
    PRIMARY KEY (id)

CREATE TABLE product (
    product_id INTEGER NOT NULL AUTO_INCREMENT,
    product_name VARCHAR(30) NOT NULL,
    price DECIMAL(2) NOT NULL VALIDATE,
    stock INTEGER NOT NULL DEFAULT 10 ISNUMERIC,
    category_id INTEGER FOREIGN KEY REFERENCES(id)
    PRIMARY KEY (product_id)
);

CREATE TABLE tag (
    tag_id INTEGER NOT NULL AUTO_INCREMENT,
    tag_name VARCHAR(30),
    PRIMARY KEY (tag_id)
);


CREATE TABLE producttag (
    pt_id INTEGER NOT NULL AUTO_INCREMENT,
    product_id INTEGER FOREIGN KEY REFERENCES(product_id),
    tag_id INTEGER FOREIGN KEY REFERENCES(tag_id),
    PRIMARY KEY (pt_id)
);





